In [1]:
"|IMPORT PACKAGES|"
import pandas             as pd
import datetime
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import ColumnDataSource,LinearAxis, Range1d, NumeralTickFormatter, LabelSet, Label, BoxAnnotation, DatetimeTickFormatter, Legend, LegendItem
from   bokeh.models.tools import HoverTool

In [7]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Argentina.xlsx?raw=true'
IO   = path + file

sheet = 'MONTHLY'

data_mensual = pd.read_excel(IO, sheet_name = sheet, skiprows=2,usecols="B,JB,JC",engine='openpyxl')
data=data_mensual.dropna()
data

         MONTH  Asalariados privados  Asalariados públicos
288 2012-01-31              6068.155              2548.429
289 2012-02-29              6062.512              2607.158
290 2012-03-31              6072.122              2620.057
291 2012-04-30              6055.222              2623.593
292 2012-05-31              6065.645              2596.534
..         ...                   ...                   ...
392 2020-09-30              5802.225              3215.571
393 2020-10-31              5798.660              3212.515
394 2020-11-30              5804.085              3230.865
395 2020-12-31              5802.666              3229.722
396 2021-01-31              5818.589              3232.103

[109 rows x 3 columns]

In [15]:
cds = ColumnDataSource(data)

#BUILD FIGURE
p = figure(title        = "EL HUB ECONÓMICO | ASALARIADOS SECTOR PRIVADO",
        
           plot_height  = 400,
           plot_width   = 700,
           x_axis_type = "datetime",
           y_axis_label = 'Asalariados privados (en millones)')

p.toolbar_location = 'right'
p.toolbar.autohide = True


#AXIS 1 (LEFT)
p1= p.line("MONTH", "Asalariados privados", color="cyan",width=2,legend_label='Asalariados privados',source=cds)  
p.legend.location     = 'top_left'
p.legend.orientation  = 'vertical'
p.legend.click_policy = 'mute'

show(p)