In [1]:
"|IMPORT PACKAGES|"
import pandas             as pd
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import LinearAxis, Range1d, ColumnDataSource, Label
from   bokeh.models.tools import HoverTool
from   bokeh.transform    import dodge

In [25]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Argentina.xlsx?raw=true'
#file = r'Resumen%20Estadistico%20-%20Argentina.xlsx'
IO   = path + file

sheet = 'PBI'

data = pd.read_excel(IO, sheet_name = sheet, usecols="A:F", skiprows=10, nrows=27, engine='openpyxl') # Be patient...
data = data.rename(columns={"%PBI (1993)":"1993"})
data = data.rename(columns={"%PBI (2004)":"2004"})
data = data.rename(columns={"2015 = 100":"Y_100"})
cds = ColumnDataSource(data)

In [16]:
"|CHECK DATA|"
data

    YEAR     PBI (1993)     PBI (2004)       1993       2004       Y_100
0   1993  236504.980232            NaN        NaN        NaN         NaN
1   1994  250307.885536            NaN   5.836201        NaN   60.292966
2   1995  243186.101519            NaN  -2.845210        NaN   58.577504
3   1996  256626.243056            NaN   5.526690        NaN   61.814901
4   1997  277441.317622            NaN   8.111047        NaN   66.828737
5   1998  288123.304608            NaN   3.850179        NaN   69.401763
6   1999  278369.013872            NaN  -3.385457        NaN   67.052196
7   2000  276172.685353            NaN  -0.788999        NaN   66.523155
8   2001  263996.674367            NaN  -4.408840        NaN   63.590256
9   2002  235235.596753            NaN -10.894485        NaN   56.662425
10  2003  256023.462375            NaN   8.837041        NaN   61.669706
11  2004  279141.288632  485115.000000   9.029573        NaN   67.238218
12  2005  304763.528550  528056.000000   9.178950   8.851716   73.189954
13  2006  330564.970472  570549.000000   8.466053   8.047063   79.079595
14  2007  359169.902946  621943.000000   8.653347   9.007815   86.202939
15  2008  383444.183250  647176.000000   6.758439   4.057124   89.700300
16  2009  386704.384733  608873.000000   0.850241  -5.918483   84.391403
17  2010  422130.052161  670524.000000   9.160917  10.125428   92.936394
18  2011  459571.104696  710782.000000   8.869554   6.003961   98.516259
19  2012  468301.016798  703486.000000   1.899578  -1.026475   97.505014
20  2013            NaN  720407.000000        NaN   2.405307   99.850309
21  2014            NaN  702306.000000        NaN  -2.512607   97.341463
22  2015            NaN  721487.000000        NaN   2.731146  100.000000
23  2016            NaN  706478.000000        NaN  -2.080287   97.919713
24  2017            NaN  725331.000000        NaN   2.668590  100.532789
25  2018            NaN  707329.642329        NaN  -2.481813   98.037753
26  2019            NaN  692030.440824        NaN  -2.162952   95.917243

In [26]:
"|BUILD PLOT|"

#BUILD FIGURE
p = figure(title        = "PBI REAL (1994 - 2019)",
           x_axis_label = "Año",
           y_axis_label = "PBI (tasa de crecimiento)",
           x_range      = (1994, 2019),
           y_range      = (-15, 15),
           plot_height  = 500,
           plot_width   = 800)

p.toolbar_location = "above"
p.toolbar.autohide = True
p.add_tools(HoverTool(tooltips = [("Año", "@YEAR"), ("%PBI (1993)", "@1993"), ("%PBI (2004)", "@2004"), ("2005=100", "@Y_100")]))


#AXIS 1 (LEFT)
p.vbar(x=dodge('YEAR', -0.20, range=p.x_range), top='1993', color="red" , width=0.25, fill_alpha=0.50, legend_label="Base 1993", source=cds)
p.vbar(x=dodge('YEAR',  0.20, range=p.x_range), top='2004', color="blue", width=0.25, fill_alpha=0.50, legend_label="Base 2004", source=cds)

#AXIS 2 (RIGHT)
p.extra_y_ranges = {"y2": Range1d(start=0, end=120)}
p.add_layout(LinearAxis(y_range_name = "y2", axis_label = "2005 = 100"), 'right')
p.line  ('YEAR', 'Y_100', color="grey", y_range_name = "y2", source=cds, legend_label="2005 = 100")
p.circle('YEAR', 'Y_100', color="grey", y_range_name = "y2", source=cds, size=7)

#LEGEND
p.legend.location     = "top_left"
p.legend.orientation  = "horizontal"
p.legend.click_policy = "mute"
show(p)

In [21]:
"|EXPORT .PNG FILE|"

export_png(p, filename="pbi_real.png")

'C:\\Users\\ncach\\OneDrive\\My Documents\\Research\\GitHub Repositories\\el-hub-economico\\static\\Jupyter Notebooks\\pbi_real.png'

In [22]:
"|# CREATE HTML FILE|"

output_file(filename="pbi_real.html", title="PBI real")
save(p)

'C:\\Users\\ncach\\OneDrive\\My Documents\\Research\\GitHub Repositories\\el-hub-economico\\static\\Jupyter Notebooks\\pbi_real.html'

In [27]:
"|CREATE JSON FILE|"
import json
import bokeh.embed

from bokeh.embed import json_item

j = json.dumps(json_item(p, "pbi_real"))
with open("pbi_real.json", "w") as fp:
    json.dump(j, fp)