In [1]:
"|IMPORT PACKAGES|"
import numpy              as np
import pandas             as pd
import datetime
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import ColumnDataSource,LinearAxis, Range1d, NumeralTickFormatter, LabelSet, Label, BoxAnnotation, DatetimeTickFormatter, Text, Span
from   bokeh.models.tools import HoverTool
from   bokeh.models       import Arrow, NormalHead, OpenHead, VeeHead
from   bokeh.transform    import dodge
from   datetime           import datetime as dt

In [2]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Argentina.xlsx?raw=true'
IO   = path + file

sheet = 'MONTHLY'

data = pd.read_excel(IO, sheet_name = sheet, usecols="B,CH, CJ:CL", skiprows=2, nrows=400, engine='openpyxl') # Be patient...

data = data.rename(columns={"Inflation IPC-C 12M"           :"INFLA"})
data = data.rename(columns={"Tiempo para duplicar precios"  :"TIEMPO1"})
data = data.rename(columns={"Tiempo para duplicar precios.1":"TIEMPO2"})
data = data.rename(columns={"Marca duplicacion de precios"  :"MARCA"})

data["INFLA"] = data["INFLA"]*100

data = data.drop(data.index[0:72])

In [3]:
"|CHECK DATA|"
data

         MONTH      INFLA   TIEMPO1  TIEMPO2  MARCA
72  1994-01-31        NaN       NaN      NaN    NaN
73  1994-02-28        NaN       NaN      NaN    NaN
74  1994-03-31        NaN       NaN      NaN    NaN
75  1994-04-30        NaN       NaN      NaN    NaN
76  1994-05-31        NaN       NaN      NaN    NaN
..         ...        ...       ...      ...    ...
395 2020-12-31  36.021400  2.253096   2Y, 3M    NaN
396 2021-01-31  38.281775  2.138530   2Y, 2M    NaN
397 2021-02-28  40.450901  2.040542   2Y, 0M    NaN
398 2021-03-31  42.490362  1.957467  1Y, 11M    NaN
399 2021-04-30  46.140361  1.826969  1Y, 10M    NaN

[328 rows x 5 columns]

In [4]:
"|BUILD PLOT|"

cds = ColumnDataSource(data)

text1  = Label(x=25, y=325, x_units='screen', y_units='screen', text_font_size="12px", text_color="darkslategrey",
               text="VARIACIÓN ANAUL")


#BUILD FIGURE
p = figure(title = "EL HUB ECONÓMICO | TIEMPO EN QUE SE DUPLICA EL NIVEL DE PRECIOS",
           y_range      = (35, 1),
           x_axis_label = "",
           y_axis_label = "",
           x_axis_type  = "datetime",
           y_axis_type  = "log",
           plot_height  = 400,
           plot_width   = 700)

p.xaxis[0].formatter = DatetimeTickFormatter(months="%b %Y")
p.toolbar_location = "right"
p.toolbar.autohide = True

#AXIS 1 (LEFT)
p.line("MONTH", "TIEMPO1" , color="red"  , line_alpha=0.75, width=2 , source=cds)
p.add_tools(HoverTool(tooltips = [("Tiempo", "@TIEMPO2"), ("Inflación", "@INFLA{0.0}")], mode="vline"))


#ADD PRICE DUPLICATION MARKS
mark1 = Span(location=dt(2004, 1,31).timestamp()*1000, dimension='height', line_color='steelblue', line_alpha=0.5)
mark2 = Span(location=dt(2008,12,31).timestamp()*1000, dimension='height', line_color='steelblue', line_alpha=0.5)
mark3 = Span(location=dt(2012, 7,31).timestamp()*1000, dimension='height', line_color='steelblue', line_alpha=0.5)
mark4 = Span(location=dt(2015, 2,28).timestamp()*1000, dimension='height', line_color='steelblue', line_alpha=0.5)
mark5 = Span(location=dt(2017, 8,31).timestamp()*1000, dimension='height', line_color='steelblue', line_alpha=0.5)
mark6 = Span(location=dt(2019,10,31).timestamp()*1000, dimension='height', line_color='steelblue', line_alpha=0.5)

text1 = Label(x=dt(2006, 6,30).timestamp()*1000, y=25, text_font_size='10px', text_color='steelblue', text_align='center',
              text='5Y')
text2 = Label(x=dt(2010,10,31).timestamp()*1000, y=25, text_font_size='10px', text_color='steelblue', text_align='center',
              text='3Y 7M')
text3 = Label(x=dt(2013,10,31).timestamp()*1000, y=25, text_font_size='10px', text_color='steelblue', text_align='center',
              text='2Y 7M')
text4 = Label(x=dt(2016, 5,31).timestamp()*1000, y=25, text_font_size='10px', text_color='steelblue', text_align='center',
              text='2Y 6M')
text5 = Label(x=dt(2018,10,31).timestamp()*1000, y=25, text_font_size='10px', text_color='steelblue', text_align='center',
              text='2Y 2M')

p.add_layout(mark1)
p.add_layout(mark2)
p.add_layout(mark3)
p.add_layout(mark4)
p.add_layout(mark5)
p.add_layout(mark6)

p.add_layout(text1)
p.add_layout(Arrow(start=VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   end  =VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   x_start=dt(2004, 1,31).timestamp()*1000, y_start=20, x_end=dt(2008,12,31).timestamp()*1000, y_end=20,
                   line_color='steelblue', line_alpha=0.5))

p.add_layout(text2)
p.add_layout(Arrow(start=VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   end  =VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   x_start=dt(2008,12,31).timestamp()*1000, y_start=20, x_end=dt(2012, 7,31).timestamp()*1000, y_end=20,
                   line_color='steelblue', line_alpha=0.5))

p.add_layout(text3)
p.add_layout(Arrow(start=VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   end  =VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   x_start=dt(2012, 7,31).timestamp()*1000, y_start=20, x_end=dt(2015, 2,28).timestamp()*1000, y_end=20,
                   line_color='steelblue', line_alpha=0.5))

p.add_layout(text4)
p.add_layout(Arrow(start=VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   end  =VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   x_start=dt(2015, 2,28).timestamp()*1000, y_start=20, x_end=dt(2017, 8,31).timestamp()*1000, y_end=20,
                   line_color='steelblue', line_alpha=0.5))
p.add_layout(text5)
p.add_layout(Arrow(start=VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   end  =VeeHead(line_color='steelblue', line_width=2, line_alpha=0.5, size=15, fill_alpha=0.5, fill_color='steelblue'),
                   x_start=dt(2017, 8,31).timestamp()*1000, y_start=20, x_end=dt(2019,10,31).timestamp()*1000, y_end=20,
                   line_color='steelblue', line_alpha=0.5))

#LEGEND
p.xaxis[0].formatter = DatetimeTickFormatter(months=['%b %Y'])
show(p)

In [ ]:
"|EXPORT .PNG FILE|"

export_png(p, filename="precios_x2.png")

In [ ]:
"|# CREATE HTML FILE|"

output_file(filename="precio_x2.html", title="Tiempo en que se duplica el nivel de precios")
save(p)

In [5]:
"|CREATE JSON FILE|"
import json
import bokeh.embed

from bokeh.embed import json_item

j = json.dumps(json_item(p, "aprecios_x2"))
with open("precios_x2.json", "w") as fp:
    json.dump(j, fp)